[manifest]
id = "ProxyMM_TransformAnywhere"
version = "0.0.3"
display_name = "TransformAnywhere"
description =  """
Allowed Transformations: All
- D-pad Up: Wishwashy
- D-pad Down: Croc (or Walrus)
- D-pad Left: Bee
- D-pad Right: Termite (or Pumpkin)
Allowed Transformations: Current World
- D-pad Up: Transform to the form from the current world, and back to Banjo.
Allowed Transformations: Banjo
- D-pad Up: Transform instantly back to Banjo only. Requires going back to Mumbo to transform.
Allowed Transformations: None
- The mod is effectively disabled

Token Payment
- Yes: Requires having paid Mumbo for the transformation in the current game file
- No: Does not require having paid Mumbo

Button Mode
- "D-pad": Only requires that the D-pad button alone be pressed for the transformation
- "L + D-pad": Requires L to be held while pressing D-pad directions for the transformation
"""
short_description = "Transform into Mumbo's forms anywhere, with optional restrictions"
authors = [ "ProxySaw" ]
game_id = "bk"
minimum_recomp_version = "0.0.1"
dependencies = []
optional_dependencies = []
native_libraries = []

[inputs]
elf_path = "../../build/packages/TransformAnywhere/mod.elf"
mod_filename = "ProxyBK_TransformAnywhere"
func_reference_syms_file = "../../BanjoRecompSyms/bk.us.rev0.syms.toml"
data_reference_syms_files = [ "../../BanjoRecompSyms/bk.us.rev0.datasyms.toml" ]
additional_files = [ "thumb.png" ]

[[manifest.config_options]]
id = "allowed_transformations"
name = "Allowed Transformations"
description = "Choose which transformations are allowed"
type = "Enum"
options = [ "All", "Current World", "Banjo", "None" ]
default = "All"

[[manifest.config_options]]
id = "token_payment"
name = "Token Payment"
description = "Choose whether token payment is required for transformations"
type = "Enum"
options = [ "No", "Yes" ]
default = "Yes"

[[manifest.config_options]]
id = "button_mode"
name = "Button Mode"
description = "Choose the button mode for transformations"
type = "Enum"
options = [ "D-pad", "L + D-pad" ]
default = "D-pad"