[manifest]
id = "ProxyMM_TransformAnywhere"
version = "0.0.1"
display_name = "TransformAnywhere"
description =  """
Transform into Mumbo's forms anywhere

- D-pad Up: Wishwashy
- D-pad Down: Croc (or Walrus)
- D-pad Left: Bee
- D-pad Right: Termite (or Pumpkin)

D-pad Up as any form returns you to Banjo. Optionally, you can require L to be held while pressing D-pad directions by enabling "Require L to Transform" in the mod settings.
"""
short_description = "Transform into Mumbo's forms anywhere"
authors = [ "ProxySaw" ]
game_id = "bk"
minimum_recomp_version = "0.0.1"
dependencies = []
optional_dependencies = []
native_libraries = []

[inputs]
elf_path = "../../build/packages/TransformAnywhere/mod.elf"
mod_filename = "ProxyBK_TransformAnywhere"
func_reference_syms_file = "../../BanjoRecompSyms/bk.us.rev0.syms.toml"
data_reference_syms_files = [ "../../BanjoRecompSyms/bk.us.rev0.datasyms.toml" ]
additional_files = [ "thumb.png" ]

[[manifest.config_options]]
id = "require_l_to_transform"
name = "Require L to Transform"
description = "Require holding the L button while pressing D-pad directions to transform"
type = "Enum"
options = [ "Off", "On" ]
default = "Off"