[manifest]
id = "ProxyBK_KV"
version = "0.0.5"
display_name = "KV"
description =  """
A simple KV Store for N64Recomp projects
"""
short_description = "A simple KV Store for N64Recomp projects"
authors = [ "ProxySaw", "LT_Schmiddy" ]
game_id = "bk"
minimum_recomp_version = "0.0.1"
dependencies = []
native_libraries = [
    { name = "ProxyRecomp_KV005", funcs = [
        "KV_PathUpdateInternal",
        "KV_Get",
        "KV_Set",
        "KV_Has",
        "KV_Remove",
        "KV_DeleteSlot",
        "KV_CopySlot"
    ] }
]

[inputs]
elf_path = "../../build/packages/KV/mod.elf"
mod_filename = "ProxyBK_KV"
func_reference_syms_file = "../../BanjoRecompSyms/bk.us.rev0.syms.toml"
data_reference_syms_files = [ "../../BanjoRecompSyms/bk.us.rev0.datasyms.toml" ]
additional_files = [ "thumb.png" ]
