[manifest]
id = "ProxyMM_ToggleTrot"
version = "0.0.1"
display_name = "ToggleTrot"
description =  """
Makes Talon Trot toggleable instead of hold-to-run

If you release Z within the first 10 frames of the toggle trot, you will not stop trotting until you press and release Z again. If you hold Z for longer than 10 frames, releasing Z will stop the trot immediately like the original behavior.
"""
short_description = "Makes Talon Trot toggleable instead of hold-to-run"
authors = [ "ProxySaw" ]
game_id = "bk"
minimum_recomp_version = "0.0.1"
dependencies = []
optional_dependencies = []
native_libraries = []

[inputs]
elf_path = "../../build/packages/ToggleTrot/mod.elf"
mod_filename = "ProxyBK_ToggleTrot"
func_reference_syms_file = "../../BanjoRecompSyms/bk.us.rev0.syms.toml"
data_reference_syms_files = [ "../../BanjoRecompSyms/bk.us.rev0.datasyms.toml" ]
additional_files = [ "thumb.png" ]
